apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
stringData:
  accessKey: "12345678790"
  secretKey: "SECRET1234"

---

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
stringData:
  accessKey: "12345678790"
  secretKey: "SECRET1234"
