apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: ashwinbittu/k8s-fleetman-queue:release2
        resources:
          requests:
            memory: 300Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  selector:
    matchLabels:
      app: position-simulator
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
      - name: position-simulator
        image: ashwinbittu/k8s-fleetman-position-simulator:release2
        envFrom:
        - configMapRef:
            name: global-configs
        resources:
          requests:
            memory: 200Mi
            cpu: 50m
        volumeMounts:
        - name: global-database-config
          mountPath: /etc/config
      volumes:
        - name: global-database-config
          configMap:
            name: global-database-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker
spec:
  selector:
    matchLabels:
      app: position-tracker
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: position-tracker
    spec:
      containers:
      - name: position-tracker
        image: ashwinbittu/k8s-fleetman-position-tracker:release3
        envFrom:
        - configMapRef:
            name: global-configs
        resources:
          requests:
            memory: 200Mi
            cpu: 50m
        volumeMounts:
        - name: global-database-config
          mountPath: /etc/config
      volumes:
        - name: global-database-config
          configMap:
            name: global-database-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 3
  template: # template for the pods
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ashwinbittu/k8s-fleetman-api-gateway:release2
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        envFrom:
        - configMapRef:
            name: global-configs
        resources:
          requests:
            memory: 300Mi
            cpu: 50m

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ashwinbittu/k8s-fleetman-webapp-angular:release2
        envFrom:
        - configMapRef:
            name: global-configs
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
